# Generated by Django 3.2.6 on 2021-09-01 12:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='Anon', max_length=50)),
                ('post', models.TextField()),
                ('posted_at', models.DateField(default=datetime.timezone)),
            ],
        ),
    ]
