# Generated by Django 3.2.6 on 2021-09-01 12:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='posted_at',
            field=models.DateField(default=datetime.datetime(2021, 9, 1, 12, 49, 26, 551890, tzinfo=utc)),
        ),
    ]
