# Generated by Django 3.2.6 on 2021-09-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20210901_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='author',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='author',
            field=models.CharField(default='Anon', max_length=50),
        ),
    ]
