# Generated by Django 3.2.6 on 2021-08-28 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_infos',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
