# Generated by Django 3.2.6 on 2021-08-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_auto_20210829_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledecorator',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
